### ISSUE TITLE
Notch placement on SK6812

### ISSUE THREAD

**Issue by artichoked1** [keebio/keebio-components#5]
Shouldn't the notch marker on the silkscreen layer be next to the ground pin instead of din?
![image](https://github.com/keebio/keebio-components/assets/41409702/ed9d4435-6ff3-4f38-bffc-5f309ed160b1)
![image](https://github.com/keebio/keebio-components/assets/41409702/ecbecf82-df5f-4841-8acb-55b73b0b7ca5)

**Comment by nooges** [comment]
You are probably using the wrong symbol on the schematic for the LED with a different pinout.

**Comment by artichoked1** [comment]
It's not about the schematic symbol, the pin numbering in the footprint is incorrect and as such, the notch should be on the opposite side.
